language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -v -s ./tests -p "*_test.py"